Update people.json
ELIXIR-NO/website pull request #21
Opened 2024-11-12 13:59 UTC by ingeborgwinge

Added Roger Simm, Peik Haugen, Gro Steine. Moved Nazeefa Fatima from UiO to UiT

2024-11-22 08:33 UTC, bianchini88 commented
@yasinmiran Can you have a look?

2024-11-22 08:38 UTC, joshbaskaran requested changes

2024-11-22 08:38 UTC, joshbaskaran commented on src/data/people.json
> +          "profile-url": https://www.mn.uio.no/ibv/english/people/adm/rogersim/",
```suggestion
          "profile-url": "https://www.mn.uio.no/ibv/english/people/adm/rogersim/",
```

2024-11-22 09:37 UTC, bianchini88 commented
@yasinmiran it looks like some would need to log into Cloudflare to see the logs, which is something we want people to be able to do, I believe. 

Anyway, just by looking at the page, I think the issue is that we are trying to use image files that are not in https://github.com/ELIXIR-NO/website/tree/ingeborgwinge-patch-4/public/assets/people. @ingeborgwinge, you would need to add pictures of the missing people.

2025-02-07 08:37 UTC, bianchini88 commented on src/data/people.json
>            "elixir-groups": [
```suggestion
          "elixir-groups": []
```

2025-02-07 08:55 UTC, bianchini88 commented on src/data/people.json
> +          "elixir-groups": []
```suggestion
          "elixir-groups": [
```

2025-02-07 10:28 UTC, bianchini88 commented on src/data/people.json
> +          "photo": "/assets/people/roger-simm.png",
```suggestion
          "photo": "/assets/people/rogersimm.jpg",
```

2025-02-07 11:28 UTC, bianchini88 commented on src/data/people.json
> +          "photo": "/assets/people/peik-haugen.png",
```suggestion
          "photo": "/assets/people/Peik-Haugen.jpeg",
```

2025-02-07 11:31 UTC, bianchini88 commented on src/data/people.json
> +          "photo": "/assets/people/Peik-Haugen.jpeg",
```suggestion
          "photo": "/assets/people/peik-haugen.jpeg",
```

2025-02-07 11:36 UTC, bianchini88 commented on src/data/people.json
> +          "photo": "/assets/people/Gro-Steine.png",
```suggestion
          "photo": "/assets/people/gro-steine.webp",
```

2025-02-07 12:28 UTC, bianchini88 commented
@korbinib @ingeborgwinge I fixed this PR, so I guess we can move forward with this. 
Tagging @joshbaskaran, as he originally requested changes back in November.

2025-02-07 12:30 UTC, joshbaskaran approved these changes
LGTM

2025-02-07 13:25 UTC, merged