feat: add funding & projects page
ELIXIR-NO/website pull request #33
Opened 2024-12-12 12:17 UTC by yasinmiran

2024-12-19 16:09 UTC, korbinib requested changes
I think in some(?) cases there is text directly used from the ELIXIR-BE page. This might be problematic regarding copyright (© 2024 ELIXIR Belgium. All Rights Reserved.), if there is no other arrangement.

I think the text from the [ELIXIR-EU pages](https://elixir-europe.org/internal-projects/commissioned-services-list) can be safely used in any case

2025-02-07 12:32 UTC, bianchini88 requested changes
All the BE-specific things should not be here.

2025-02-07 12:32 UTC, bianchini88 commented on src/content/projects/done/by-covid.mdx
> +**ELIXIR Belgium** is involved in and contributing to [WP4: Connecting the COVID-19 platform to analysis tools and local portals](https://by-covid.org/about#structure). Specifically, WP4 will develop
This is BE-specific

2025-02-07 12:32 UTC, bianchini88 commented on src/content/projects/done/elixir-converge.mdx
> +**ELIXIR Belgium** is involved in and contributing to:-
This is BE-specific

2025-02-07 12:32 UTC, bianchini88 commented on src/content/projects/done/elixir-steers.mdx
> +ELIXIR Belgium is leading [WP3: Infrastructure services to enable adoption and deployment of software best practice](https://elixir-europe.org/about-us/how-funded/eu-projects/steers/wp3) and contribu
This is BE-specific

2025-02-07 12:32 UTC, bianchini88 commented on src/content/projects/done/eosc-entrust.mdx
> +**ELIXIR Belgium** contributes to sharing know-how on the technologies developed in Belgium to support the creation of a European blueprint on TREs functioning and how they can be integrated into the
This is BE-specific

2025-02-07 12:32 UTC, bianchini88 commented on src/content/projects/done/eosc-life.mdx
> +ELIXIR Belgium (VIB) is involved in the work package “**Tools Collaboratory: Deployment of life-science data integration and analysis workflows in EOSC**” (WP2). WP leads are Antonio Rosato (Instruct
This is BE-specific

2025-02-07 12:32 UTC, bianchini88 commented on src/content/projects/done/euro-science-gateway.mdx
> +ELIXIR Belgium is involved and contributing to
This is BE-specific

2025-02-07 12:32 UTC, bianchini88 commented on src/content/projects/done/excelerate.mdx
> +ELIXIR Belgium is involved in two work packages.
This is BE-specific

2025-02-07 12:32 UTC, bianchini88 commented on src/content/projects/done/genome-of-europe.mdx
> +ELIXIR Belgium primarily contributes to Work Package 4 on Data Infrastructure, focusing on enabling the submission and analysis of GoE data within the 1+MG data infrastructure developed by the GDI pr
This is BE-specific

2025-02-07 12:32 UTC, bianchini88 commented on src/content/projects/done/genomic-data-infrastructure.mdx
> +VIB/ELIXIR Belgium and Sciensano are involved in Pillar I (Long-term sustainability, work package 2) bringing together country representatives to agree on a long-term governance model, a legal framew
This is BE-specific

2025-02-07 12:32 UTC, bianchini88 commented on src/content/projects/done/genomic-data-infrastructure.mdx
> +VIB/ELIXIR Belgium and Sciensano are also contributing to Pillar II (Infrastructure deployment), by rolling out the federated infrastructure in Belgium and making this useful for research and diagnos
This is BE-specific

2025-02-07 12:37 UTC, bianchini88 commented
This cannot be merged until all the BE-specific content is removed (there was some more in the new commit). @korbinib was also mentioning copyright issues, which makes me think it is not a good idea to merge this.

2025-02-07 12:38 UTC, bianchini88 commented
@ingeborgwinge I am moving this back to draft, as this is very far from something that can be published.

2025-02-26 08:38 UTC, bianchini88 commented
Decision after voting at the meeting yesterday: delete all the content and keep the structure.

2025-02-28 11:03 UTC, bianchini88 approved these changes

2025-02-28 11:12 UTC, korbinib approved these changes

2025-02-28 11:30 UTC, merged